In [1]:
# Loading libraries
import pandas as pd
import numpy as np

C:\Users\Asante\anaconda 3\lib\site-packages\pandas\core\arrays\masked.py:62: UserWarning: Pandas requires version '1.3.4' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (


In [21]:
# Checking pandas version
pd.__version__

'2.1.0'

In [22]:
# Loading data
df = pd.read_csv('data.csv')

In [23]:
# Checking number of rows and columns: (rows, columns)
df.shape

(20640, 10)

In [24]:
# Checking missing values and other info about data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [25]:
# Computing the average of 'median_house_value'
df[df['ocean_proximity']=='NEAR BAY']['median_house_value'].mean()

259212.31179039303

In [26]:
# Computing the average of total_bedrooms
mn = df['total_bedrooms'].mean()
mn

537.8705525375618

In [27]:
# Filling missing values in the total_bedrooms column
df['total_bedrooms'] = df['total_bedrooms'].fillna(mn)
df['total_bedrooms'].mean()

537.8705525375617

In [50]:
# checking 
print (f"Number of unique values is: {df['ocean_proximity'].nunique()}")
print (df['ocean_proximity'].value_counts())

Number of unique values is: 5
ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64


In [34]:
# Selecting only Islands and casting the results to a numpy array
island = df[df['ocean_proximity']=='ISLAND']
X = island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
X = np.array(X)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [36]:
# Matrix multiplication using the dot product
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [40]:
# Finding the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [41]:
# Forming array y
y = [950, 1300, 800, 1000, 1300]

In [44]:
# Finding the product of XTX_inv, X transpose and y
w = XTX_inv.dot(X.T).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])